### ISSUE TITLE
Create User Story for New Feature

### ISSUE THREAD

**Issue by codyschlabach** [cs361fall2017/team39#24]
Create a user story for the new feature: "Implement the regular AcesUp rules, but include a new rule that only the Ace cards can be moved into empty piles (except during the initial deal that starts the game)."

Note: add this user story to the new wiki page - “Sprint 3 User Story”

**Comment by sharlenaluyen** [comment]
As a user, I want to move nothing but "Ace" cards into empty spaces so that I can challenge myself in this game/add a new rule to the game.
